image: nfcore/gitpod:latest

# # Manual Quarto install - mamba version doesn't work correctly
# tasks:
#   - name: Install Quarto
#     command: |
#       wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb && \
#       sudo dpkg -i quarto-1.3.450-linux-amd64.deb && \
#       rm quarto-1.3.450-linux-amd64.deb

vscode:
  extensions:
    - quarto.quarto
    - esbenp.prettier-vscode
    - nextflow.nextflow
